### ISSUE TITLE
CRITICAL: Exposed Discord API Token in Codebase 

### ISSUE THREAD

**Issue by devsargam** [NawinKumarSharma/Discord-Bot#1]
https://github.com/NawinKumarSharma/Discord-Bot/blob/330b9b218fa65f2e1afcf5157b5d49fe6a358419/command.js#L11

https://github.com/NawinKumarSharma/Discord-Bot/blob/330b9b218fa65f2e1afcf5157b5d49fe6a358419/index.js#L43

**Comment by nawinsharma** [comment]
Thank you for bringing this critical issue to our attention.
The token in our codebase is a dummy token intentionally used for security reasons. We never store actual Discord API Tokens in our GitHub repository to prevent exposure. The genuine Discord API Toke­n is securely managed and ke­pt outside of the codebase­. You need to create your own API token for running the bot.

**Comment by devsargam** [comment]
This is a bad practice.
Use the dotenv package from npm registry for these secrets
[dotenv](https://www.npmjs.com/package/dotenv)

**Comment by nawinsharma** [comment]
Thank you for your comment and for pointing out the use of the `dotenv` package for managing secrets. I appreciate your input to the project.
